package tiketpesawatcrud;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Durian
 */
public class formTiket extends javax.swing.JFrame {
 private int idLogin;
    /**
     * Creates new form formTiket
     * @param username
     */
    public formTiket(int idLogin) {
        this.idLogin = idLogin;
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
//        scaleBg();
    }
//   private void scaleBg() {
//    // Load the original image
//    ImageIcon icon = new ImageIcon("C:\\Users\\Durian\\OneDrive\\Documents\\NetBeansProjects\\tiketpesawatCRUD\\src\\images\\airplane.png");
//    Image img = icon.getImage();
//
//    // Calculate the aspect ratio of the original image
//    double aspectRatio = (double) img.getWidth(null) / img.getHeight(null);
//
//    // Define the target dimensions
//    int targetWidth = 1920;
//    int targetHeight = 1080;
//
//    // Calculate the scaled dimensions while preserving aspect ratio
//    int scaledWidth = targetWidth;
//    int scaledHeight = (int) (scaledWidth / aspectRatio);
//
//    // If the scaled height exceeds the target height, adjust the dimensions
//    if (scaledHeight > targetHeight) {
//        scaledHeight = targetHeight;
//        scaledWidth = (int) (scaledHeight * aspectRatio);
//    }
//
//    // Scale the image
//    Image scaledImg = img.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);
//
//    // Create a scaled ImageIcon
//    ImageIcon scaledIcon = new ImageIcon(scaledImg);
//
//    // Set the scaled image as the icon for bg component
//    bg.setIcon(scaledIcon);
//}
//
//
//private Image cropImage(Image img, int x, int y, int width, int height) {
//    // Create a new image with the specified width and height
//    BufferedImage croppedImg = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
//
//    // Create a graphics object to draw the cropped image
//    Graphics2D g2d = croppedImg.createGraphics();
//
//    // Draw the portion of the original image specified by the cropping rectangle onto the new image
//    g2d.drawImage(img, 0, 0, width, height, x, y, x + width, y + height, null);
//
//    // Dispose the graphics object
//    g2d.dispose();

    // Return the cropped image
//    return croppedImg;
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        crudCust = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        crudPesanTiket = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        crudTerbang = new javax.swing.JMenuItem();
        crudrute = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        jDesktopPane1.setLayer(bg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenu1.setText("Customer");

        crudCust.setText("CRUD Customer");
        crudCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudCustActionPerformed(evt);
            }
        });
        jMenu1.add(crudCust);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pemesanan Ticket");

        crudPesanTiket.setText("CRUD Pemesanan Ticket");
        crudPesanTiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudPesanTiketActionPerformed(evt);
            }
        });
        jMenu2.add(crudPesanTiket);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Penerbangan");

        crudTerbang.setText("CRUD Penerbangan");
        crudTerbang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudTerbangActionPerformed(evt);
            }
        });
        jMenu3.add(crudTerbang);

        crudrute.setText("CRUD Rute");
        crudrute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crudruteActionPerformed(evt);
            }
        });
        jMenu3.add(crudrute);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crudCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudCustActionPerformed
        // TODO add your handling code here:
         crudCustomer ccust = new crudCustomer();
        jDesktopPane1.add(ccust);
        ccust.setVisible(true);
    }//GEN-LAST:event_crudCustActionPerformed

    private void crudPesanTiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudPesanTiketActionPerformed
        // TODO add your handling code here:
        crudPemesanan cPem = new crudPemesanan(idLogin);
        jDesktopPane1.add(cPem);
        cPem.setVisible(true);
    }//GEN-LAST:event_crudPesanTiketActionPerformed

    private void crudruteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudruteActionPerformed
        // TODO add your handling code here:
        crudRute cRute = new crudRute();
        jDesktopPane1.add(cRute);
        cRute.setVisible(true);
    }//GEN-LAST:event_crudruteActionPerformed

    private void crudTerbangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crudTerbangActionPerformed
        // TODO add your handling code here:
        crudPenerbangan cPen = new crudPenerbangan();
        jDesktopPane1.add(cPen);
        cPen.setVisible(true);
    }//GEN-LAST:event_crudTerbangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTiket(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JMenuItem crudCust;
    private javax.swing.JMenuItem crudPesanTiket;
    private javax.swing.JMenuItem crudTerbang;
    private javax.swing.JMenuItem crudrute;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
